# Dependencies are managed in the Dockerfile in the inkscape-ci-docker
# Git repository. Change them there, wait a bit, and then we'll use
# the new ones here in these builds.
image: registry.gitlab.com/inkscape/inkscape-ci-docker/extensions

variables:
  GIT_DEPTH: "10"
  GIT_SUBMODULE_STRATEGY: recursive


test:python2:
  script:
    - python2 setup.py test

test:python3:
  script:
    - python3 setup.py test
