Content-Type: multipart/mixed; boundary="--CALLDATA--//--CALLDATA--"
MIME-Version: 1.0
Program: inkscape
Arguments: --export-dpi=1.0 --export-png=Layer 1.png --without-gui Layer 1.svg

----CALLDATA--//--CALLDATA--
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

RFBJOiAxCkJhY2tncm91bmQgUlJHR0JCQUE6IGZmZmZmZjAwCkFyZWEgMDowOjc5My43MDE6MTEy
Mi41MiBleHBvcnRlZCB0byA4IHggMTIgcGl4ZWxzICgxIGRwaSkKQml0bWFwIHNhdmVkIGFzOiAv
dG1wL2plc3N5SW5rLTB6Mm9zZWY2L0xheWVyIDEucG5nCg==

----CALLDATA--//--CALLDATA--
Content-Type: application/octet-stream; Name="Layer 1.png"
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment
Filename: Layer 1.png

iVBORw0KGgoAAAANSUhEUgAAAAgAAAAMCAYAAABfnvydAAAABHNCSVQICAgIfAhkiAAAAAlwSFlz
AAAAJwAAACcBKgmRTwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAAOSURB
VBiVY2AYBYMFAAABjAABCm+lXwAAAABJRU5ErkJggg==

----CALLDATA--//--CALLDATA----
