Content-Type: multipart/mixed; boundary="--CALLDATA--//--CALLDATA--"
MIME-Version: 1.0
Program: inkscape
Arguments: --export-dpi=1.0 --export-png=Slide2.png --without-gui Slide2.svg

----CALLDATA--//--CALLDATA--
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

RFBJOiAxCkJhY2tncm91bmQgUlJHR0JCQUE6IGZmZmZmZjAwCkFyZWEgMDowOjEwMDA6MTAwMCBl
eHBvcnRlZCB0byAxMCB4IDEwIHBpeGVscyAoMSBkcGkpCkJpdG1hcCBzYXZlZCBhczogL3RtcC9q
ZXNzeUluay13MzVsMHFtbi9TbGlkZTIucG5nCg==

----CALLDATA--//--CALLDATA--
Content-Type: application/octet-stream; Name="Slide2.png"
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment
Filename: Slide2.png

iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAABHNCSVQICAgIfAhkiAAAAAlwSFlz
AAAAJwAAACcBKgmRTwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAACfSURB
VBiVzdAvbgJxEMXxzw8WFkFag0XxRxBOQEKCwOwRegEcJ8Csp6oGBQkWg+IWpEkNHICeYC+wCBZC
CHiemZeZl+9khvdQTpQTgR+xVPU6K11KussvPkEymagsBn6/+rb3oAhlhD2VG3Eqlqo9BpfoolVs
aRe+g3BLjr41EEYb9aIVPCjA+s/8P3NsfuidMofZ0OrptVfSeOPz1UfORNsakYMQdQgAAAAASUVO
RK5CYII=

----CALLDATA--//--CALLDATA----
