Content-Type: multipart/mixed; boundary="--CALLDATA--//--CALLDATA--"
MIME-Version: 1.0
Program: inkscape
Arguments: --export-dpi=1.0 --export-png=Slide1.png --without-gui Slide1.svg

----CALLDATA--//--CALLDATA--
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

RFBJOiAxCkJhY2tncm91bmQgUlJHR0JCQUE6IGZmZmZmZjAwCkFyZWEgMDowOjEwMDA6MTAwMCBl
eHBvcnRlZCB0byAxMCB4IDEwIHBpeGVscyAoMSBkcGkpCkJpdG1hcCBzYXZlZCBhczogL3RtcC9q
ZXNzeUluay13MzVsMHFtbi9TbGlkZTEucG5nCg==

----CALLDATA--//--CALLDATA--
Content-Type: application/octet-stream; Name="Slide1.png"
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment
Filename: Slide1.png

iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAABHNCSVQICAgIfAhkiAAAAAlwSFlz
AAAAJwAAACcBKgmRTwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAABhSURB
VBiV5cqxCYNQGIXR8yyCoFUQUtg7g6Wjvd5xUkpGMQu4QRL4LXyFzpADl9t8yeFWPsrg56Qq/wm+
b+4vHhNkrVnjKkfQBWMwPgf9stqW1SarL2mQStwFyayRtf7aDmB0GeimYVg0AAAAAElFTkSuQmCC

----CALLDATA--//--CALLDATA----
