Content-Type: multipart/mixed; boundary="--CALLDATA--//--CALLDATA--"
MIME-Version: 1.0
Program: inkscape
Arguments: --export-dpi=1.0 --export-png=Slide3.png --without-gui Slide3.svg

----CALLDATA--//--CALLDATA--
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

RFBJOiAxCkJhY2tncm91bmQgUlJHR0JCQUE6IGZmZmZmZjAwCkFyZWEgMDowOjEwMDA6MTAwMCBl
eHBvcnRlZCB0byAxMCB4IDEwIHBpeGVscyAoMSBkcGkpCkJpdG1hcCBzYXZlZCBhczogL3RtcC9q
ZXNzeUluay13MzVsMHFtbi9TbGlkZTMucG5nCg==

----CALLDATA--//--CALLDATA--
Content-Type: application/octet-stream; Name="Slide3.png"
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment
Filename: Slide3.png

iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAABHNCSVQICAgIfAhkiAAAAAlwSFlz
AAAAJwAAACcBKgmRTwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAAxSURB
VBiVY2AYMMCIS+I/A4MsAwODHFTRURY8higxMDA4Qtl4FT5hYGA4TqoTBxIAAB8wBN3ExhlmAAAA
AElFTkSuQmCC

----CALLDATA--//--CALLDATA----
